# Pre-commit hooks for finch-buck2
# Run code quality checks before each commit

repos:
  # Basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # C++ formatting and linting
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i]
        types_or: [c++, c]
        exclude: ^(buck2/|build/)
      - id: clang-tidy
        args: [-p=build]
        types_or: [c++, c]
        exclude: ^(buck2/|build/)

  # Additional C++ linting
  - repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
      - id: cpplint
        args:
          - --filter=-legal/copyright,-build/include_subdir,-build/c++11,-runtime/references
          - --linelength=100
        types_or: [c++, c]
        exclude: ^(buck2/|build/|test/)

  # CMake formatting
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: [--in-place]
        types: [cmake]
        exclude: ^buck2/

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [-e, SC1091] # Don't follow sourced files

  # Python formatting (for any scripts)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix]
        exclude: ^(CHANGELOG\.md|buck2/)

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^buck2/

# Global exclusions
exclude: |
  (?x)^(
    buck-out/.*|
    build/.*|
    \.git/.*|
    .*\.patch
  )$

# Configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: 3.0.0
